### ISSUE TITLE
Description is misleading

### ISSUE THREAD

**Issue by nanaian** [n4ru/FluiDB#2]
> Light-weight **async** JSON database with low dependency overhead.

FluiDB is most definitely **not** async:

https://github.com/n4ru/FluiDB/blob/master/index.js#L14:
>`fs.writeFileSync(this.file, JSON.stringify(...));`

writeFileSync is blocking :(

**Comment by n4ru** [comment]
Oops, should be using the async function. Will fix.

**Comment by towerofnix** [comment]
Depending on the programming style you use, you should probably make it work with [promises](http://2ality.com/2017/05/util-promisify.html) or [callbacks](https://stackoverflow.com/a/10058879). Right now your code probably does not work very well if you try to do two fs actions fairly quickly (though storing `this.db` the way you do *might* let you get away with it).

(But obviously you can't do `await (db.foo = 'bar')` or whatever, since you can't really return anything from `db.foo = 'bar'`. So I'm not sure how you should do something async in a proxy handler!)

**Comment by n4ru** [comment]
I've tried to make the library as simple as possible (maybe a bit too simple...). I'll likely be adding an options parameter that can be passed an object for certain things like choosing sync/async.
